### ISSUE TITLE
Old (deleted) projects still show up at `Recent Projects` tab

### ISSUE THREAD

**Issue by luiztauffer** [flatironinstitute/dendro-old#140]
Most of the projects listed in my `Recent Projects` tab were deleted already.

![image](https://github.com/flatironinstitute/dendro/assets/24541631/a5c37662-9449-4077-9acd-819572b12270)

**Comment by magland** [comment]
This should be fixed now (or in a few minutes after deploy).

After deleting a project, refresh the page.

**Comment by luiztauffer** [comment]
thanks!
